# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aea7e1bd4798ab0869294cfa05cf7c68e412e94e0e01f8f344b0b74eb216ce6dca489c6c9c0bfb4e16b41c7d4fa08bae1f33b2524d924ac676dcfbdb167c278d

test:
  secret_key_base: c7570bc67ea439794d40808da60b9660abe9ffd6e9ce346d79ec8ce2cc8f9b7ca8995208eb7a39cfc6c4438c3fcfa748dc8f48517eb39585944c7c42bee2a915

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
